import Head from 'next/head';
import About from '../components/About';
import Main from '../components/Main';
import Navbar from '../components/Navbar';
import Skills from '../components/Skills';
import Projetos from '../components/Projects';
import Experiences from '../components/Experiences';
import Contact from '../components/Contact';

function Home() {
  return (
    <>
      <Head>
        <title>Juan Costa | Desenvolvedor Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio-juan/public/favicon.png" type="image/png" />
      </Head>

      <Navbar />
      <Main />
      <About />
      <Experiences />
      <Skills />
      <Projetos />
      <Contact />
    </>
  );
}

export default Home;
